"""Per-target hook configuration rendering.

Sources from `plugins/elixir-phoenix/hooks/hooks.json` and the 19 shell scripts
under `plugins/elixir-phoenix/hooks/scripts/`.

Per-target event support:

    Claude:    9 events (PreToolUse, PostToolUse, PostToolUseFailure,
               SubagentStart, SessionStart, PreCompact, PostCompact,
               StopFailure, Stop)
    Codex:     6 of 9 — drops PostToolUseFailure, SubagentStart, StopFailure
    OpenCode:  TS hooks module (Phase 2B), maps event names to OpenCode hooks
    Pi:        TS extension (Phase 2C), `tool_call` interceptor +
               `session_start`. Hooks-as-code rather than hooks-as-config.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

# ---- Codex --------------------------------------------------------------

# Events Codex's hooks system supports today (Phase 2A). Anything else is
# silently dropped from the generated `targets/codex/hooks/hooks.json`.
CODEX_SUPPORTED_EVENTS = {
    "PreToolUse",
    "PostToolUse",
    "SessionStart",
    "Stop",
    "PreCompact",
    "PostCompact",
}

# Source-only events (no Codex equivalent). Documented in `docs/multi-agent/codex.md`.
CODEX_DROPPED_EVENTS = {"PostToolUseFailure", "SubagentStart", "StopFailure"}


def render_codex_hooks(
    source_hooks_dir: Path, source_hooks_json: Path, out_dir: Path
) -> dict:
    """Generate `targets/codex/hooks/{hooks.json,scripts/*.sh}`.

    Rewrites `${CLAUDE_PLUGIN_ROOT}` to `${CODEX_PLUGIN_ROOT}` in script paths
    inside `hooks.json`. Shell scripts are copied verbatim — they're
    file/syscall side-effecty and don't reference Claude internals.
    """
    out_hooks_dir = out_dir / "hooks"
    out_scripts_dir = out_hooks_dir / "scripts"
    if out_scripts_dir.exists():
        shutil.rmtree(out_scripts_dir)
    out_scripts_dir.mkdir(parents=True, exist_ok=True)

    # Copy all source scripts. Their content is bash and target-agnostic.
    copied_scripts = 0
    for script in source_hooks_dir.glob("*.sh"):
        dest = out_scripts_dir / script.name
        shutil.copyfile(script, dest)
        dest.chmod(0o755)
        copied_scripts += 1

    # Rewrite hooks.json: keep only supported events, swap PLUGIN_ROOT var.
    source = json.loads(source_hooks_json.read_text(encoding="utf-8"))
    out_hooks: dict[str, list] = {}
    dropped: list[str] = []

    for event, configs in (source.get("hooks") or {}).items():
        if event not in CODEX_SUPPORTED_EVENTS:
            dropped.append(event)
            continue
        rewritten = json.loads(
            json.dumps(configs).replace("${CLAUDE_PLUGIN_ROOT}", "${CODEX_PLUGIN_ROOT}")
        )
        out_hooks[event] = rewritten

    out_doc = {"hooks": out_hooks, "_meta": {"dropped_events": sorted(dropped)}}
    (out_hooks_dir / "hooks.json").write_text(
        json.dumps(out_doc, indent=2) + "\n", encoding="utf-8"
    )

    # Generate SessionStart helper that drops sub-agent TOMLs into ~/.codex/agents/
    install_agents = out_scripts_dir / "install-codex-agents.sh"
    install_agents.write_text(
        "#!/usr/bin/env bash\n"
        "# SessionStart hook: copy bundled sub-agent TOMLs into ~/.codex/agents/.\n"
        'set -eu\n'
        'TARGET_DIR="${HOME}/.codex/agents"\n'
        'PLUGIN_ROOT="${CODEX_PLUGIN_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"\n'
        'SOURCE_DIR="${PLUGIN_ROOT}/agents-toml"\n'
        '[ -d "$SOURCE_DIR" ] || exit 0\n'
        'mkdir -p "$TARGET_DIR"\n'
        'cp -f "$SOURCE_DIR"/*.toml "$TARGET_DIR/" 2>/dev/null || true\n'
        'echo "[install-codex-agents] copied $(ls "$SOURCE_DIR"/*.toml 2>/dev/null | wc -l) agents"\n',
        encoding="utf-8",
    )
    install_agents.chmod(0o755)

    return {
        "scripts_copied": copied_scripts + 1,
        "events_kept": sorted(out_hooks.keys()),
        "events_dropped": sorted(dropped),
    }


# ---- OpenCode -----------------------------------------------------------

OPENCODE_SERVER_TS = '''/**
 * OpenCode server hooks for elixir-phoenix.
 *
 * Generated by scripts/port.py from plugins/elixir-phoenix/hooks/.
 * Source-of-truth: do NOT edit by hand — edit the source plugin and run `make port`.
 */

import type { Plugin } from "@opencode-ai/plugin";

export const Hooks: Plugin = {
  // PreToolUse — block dangerous ops (mix ecto.reset, git push --force, MIX_ENV=prod).
  "tool.execute.before": async ({ tool, args }) => {
    if (tool === "Bash") {
      const cmd = (args?.command ?? "") as string;
      if (/mix\\s+ecto\\.(reset|drop)/.test(cmd)) {
        throw new Error("BLOCKED: destructive ecto operation. Use a migration instead.");
      }
      if (/git\\s+push\\s+.*--force/.test(cmd)) {
        throw new Error("BLOCKED: --force push. Use --force-with-lease at minimum.");
      }
      if (/MIX_ENV=prod/.test(cmd)) {
        throw new Error("BLOCKED: MIX_ENV=prod in dev session. Targeting prod env locally is rarely intended.");
      }
    }
  },

  // PostToolUse — format Elixir, verify Iron Laws, warn on debug statements.
  "tool.execute.after": async ({ tool, args, result }) => {
    if (tool === "Edit" || tool === "Write") {
      const path = (args?.file_path ?? args?.path ?? "") as string;
      if (path.endsWith(".ex") || path.endsWith(".exs")) {
        // Side-effect handlers (format, iron-law-verifier, debug-statement-warning)
        // are spawned as bash subprocesses to keep parity with the Claude pipeline.
        const { spawnSync } = await import("child_process");
        const pluginRoot = process.env.OPENCODE_PLUGIN_ROOT ?? ".";
        const scripts = [
          `${pluginRoot}/hooks/scripts/format-elixir.sh`,
          `${pluginRoot}/hooks/scripts/iron-law-verifier.sh`,
          `${pluginRoot}/hooks/scripts/debug-statement-warning.sh`,
        ];
        for (const script of scripts) {
          spawnSync("bash", [script], { env: { ...process.env, FILE_PATH: path } });
        }
      }
    }
  },

  // experimental.chat.system.transform — inject Iron Laws at conversation start
  // (cleaner equivalent of Claude's SubagentStart hook).
  "experimental.chat.system.transform": async ({ system }) => {
    const ironLaws = await loadIronLaws();
    return `${system}\\n\\n${ironLaws}`;
  },

  // event filter — SessionStart-equivalent. Currently a no-op; placeholder for
  // future workflow-state restoration.
  event: async ({ event }) => {
    if (event === "session.start") {
      // setup hooks, warm caches, etc.
    }
  },
};

async function loadIronLaws(): Promise<string> {
  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  const root = process.env.OPENCODE_PLUGIN_ROOT ?? ".";
  const yamlPath = path.join(root, "iron-laws", "laws.yaml");
  try {
    const yaml = await import("yaml");
    const content = await fs.readFile(yamlPath, "utf-8");
    const data = yaml.parse(content) ?? {};
    const bullets = (data.laws ?? [])
      .filter((law: any) => law.shortform)
      .map((law: any) => `- ${law.shortform}`)
      .join("\\n");
    return `Elixir/Phoenix Iron Laws (NON-NEGOTIABLE):\\n${bullets}`;
  } catch {
    return "Elixir/Phoenix Iron Laws available in iron-laws/laws.yaml";
  }
}
'''


def render_opencode_server_ts(out_dir: Path) -> dict:
    """Write `targets/opencode/server.ts` with the full hooks module."""
    (out_dir / "server.ts").write_text(OPENCODE_SERVER_TS, encoding="utf-8")
    return {"server_ts": "generated"}


def render_opencode_mcp_block(out_dir: Path) -> None:
    """Drop a Tidewave MCP config snippet at `targets/opencode/opencode.mcp.json`.

    Users splice this into their `opencode.json` `mcp` block — we don't ship
    `opencode.json` itself because that's the user's per-project config.
    """
    snippet = {
        "mcp": {
            "tidewave": {
                "type": "http",
                "url": "http://localhost:4000/tidewave/mcp",
            }
        }
    }
    (out_dir / "opencode.mcp.json").write_text(
        json.dumps(snippet, indent=2) + "\n", encoding="utf-8"
    )


# ---- Pi -----------------------------------------------------------------

PI_IRON_LAWS_TS = '''/**
 * Pi extension: Iron Laws.
 *
 * Hooks two Pi events:
 *   - session_start — injects all 22 Iron Laws into the conversation prefix
 *   - tool_call     — intercepts dangerous ops (mix ecto.reset, force push)
 *
 * Generated by scripts/port.py — edit `plugins/elixir-phoenix/` source and re-run.
 */

import type { Pi } from "@pi-ai/extensions";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import yaml from "yaml";

export default function(pi: Pi) {
  pi.on("session_start", () => {
    const lawsPath = join(pi.root, "iron-laws", "laws.yaml");
    try {
      const data = yaml.parse(readFileSync(lawsPath, "utf-8"));
      const lines = (data.laws ?? [])
        .filter((law: any) => law.shortform)
        .map((law: any) => `- ${law.shortform}`)
        .join("\\n");
      pi.system_prompt_append(`Elixir/Phoenix Iron Laws (NON-NEGOTIABLE):\\n${lines}`);
    } catch {
      // Best-effort. Pi continues without Iron Laws if YAML is missing.
    }
  });

  pi.on("tool_call", (call) => {
    if (call.tool !== "bash") return;
    const cmd: string = call.args?.command ?? "";
    if (/mix\\s+ecto\\.(reset|drop)/.test(cmd)) {
      call.block("BLOCKED: destructive ecto operation. Use a migration instead.");
    }
    if (/git\\s+push\\s+.*--force/.test(cmd)) {
      call.block("BLOCKED: --force push. Use --force-with-lease at minimum.");
    }
  });
}
'''

PI_ORCHESTRATION_TS = '''/**
 * Pi extension: orchestration (Plan → Work → Review).
 *
 * Phase 2C scaffold. The full Plan/Work/Review cycle dispatches Pi prompt
 * templates from `prompts/<name>.md`. Decision: native Pi events vs.
 * @tintinweb/pi-subagents — see docs/multi-agent/pi.md.
 *
 * For 2.9.x this is a pass-through; full sub-agent dispatch lands in 3.0.0.
 */

import type { Pi } from "@pi-ai/extensions";

export default function(pi: Pi) {
  pi.command("phx-plan", async (args, ctx) => {
    return ctx.invoke_prompt("phx-plan", { args });
  });
  pi.command("phx-work", async (args, ctx) => {
    return ctx.invoke_prompt("phx-work", { args });
  });
  pi.command("phx-review", async (args, ctx) => {
    return ctx.invoke_prompt("phx-review", { args });
  });
}
'''


def render_pi_extensions(out_dir: Path) -> dict:
    ext_dir = out_dir / "extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)
    (ext_dir / "iron-laws.ts").write_text(PI_IRON_LAWS_TS, encoding="utf-8")
    (ext_dir / "orchestration.ts").write_text(PI_ORCHESTRATION_TS, encoding="utf-8")
    return {"extensions": ["iron-laws.ts", "orchestration.ts"]}
