/**
 * OpenCode server hooks for elixir-phoenix.
 *
 * Generated by scripts/port.py from plugins/elixir-phoenix/hooks/.
 * Source-of-truth: do NOT edit by hand — edit the source plugin and run `make port`.
 */

import type { Plugin } from "@opencode-ai/plugin";

export const Hooks: Plugin = {
  // PreToolUse — block dangerous ops (mix ecto.reset, git push --force, MIX_ENV=prod).
  "tool.execute.before": async ({ tool, args }) => {
    if (tool === "Bash") {
      const cmd = (args?.command ?? "") as string;
      if (/mix\s+ecto\.(reset|drop)/.test(cmd)) {
        throw new Error("BLOCKED: destructive ecto operation. Use a migration instead.");
      }
      if (/git\s+push\s+.*--force/.test(cmd)) {
        throw new Error("BLOCKED: --force push. Use --force-with-lease at minimum.");
      }
      if (/MIX_ENV=prod/.test(cmd)) {
        throw new Error("BLOCKED: MIX_ENV=prod in dev session. Targeting prod env locally is rarely intended.");
      }
    }
  },

  // PostToolUse — format Elixir, verify Iron Laws, warn on debug statements.
  "tool.execute.after": async ({ tool, args, result }) => {
    if (tool === "Edit" || tool === "Write") {
      const path = (args?.file_path ?? args?.path ?? "") as string;
      if (path.endsWith(".ex") || path.endsWith(".exs")) {
        // Side-effect handlers (format, iron-law-verifier, debug-statement-warning)
        // are spawned as bash subprocesses to keep parity with the Claude pipeline.
        const { spawnSync } = await import("child_process");
        const pluginRoot = process.env.OPENCODE_PLUGIN_ROOT ?? ".";
        const scripts = [
          `${pluginRoot}/hooks/scripts/format-elixir.sh`,
          `${pluginRoot}/hooks/scripts/iron-law-verifier.sh`,
          `${pluginRoot}/hooks/scripts/debug-statement-warning.sh`,
        ];
        for (const script of scripts) {
          spawnSync("bash", [script], { env: { ...process.env, FILE_PATH: path } });
        }
      }
    }
  },

  // experimental.chat.system.transform — inject Iron Laws at conversation start
  // (cleaner equivalent of Claude's SubagentStart hook).
  "experimental.chat.system.transform": async ({ system }) => {
    const ironLaws = await loadIronLaws();
    return `${system}\n\n${ironLaws}`;
  },

  // event filter — SessionStart-equivalent. Currently a no-op; placeholder for
  // future workflow-state restoration.
  event: async ({ event }) => {
    if (event === "session.start") {
      // setup hooks, warm caches, etc.
    }
  },
};

async function loadIronLaws(): Promise<string> {
  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  const root = process.env.OPENCODE_PLUGIN_ROOT ?? ".";
  const yamlPath = path.join(root, "iron-laws", "laws.yaml");
  try {
    const yaml = await import("yaml");
    const content = await fs.readFile(yamlPath, "utf-8");
    const data = yaml.parse(content) ?? {};
    const bullets = (data.laws ?? [])
      .filter((law: any) => law.shortform)
      .map((law: any) => `- ${law.shortform}`)
      .join("\n");
    return `Elixir/Phoenix Iron Laws (NON-NEGOTIABLE):\n${bullets}`;
  } catch {
    return "Elixir/Phoenix Iron Laws available in iron-laws/laws.yaml";
  }
}
