/**
 * Pi extension: Iron Laws.
 *
 * Hooks two Pi events:
 *   - session_start — injects all 22 Iron Laws into the conversation prefix
 *   - tool_call     — intercepts dangerous ops (mix ecto.reset, force push)
 *
 * Generated by scripts/port.py — edit `plugins/elixir-phoenix/` source and re-run.
 */

import type { Pi } from "@pi-ai/extensions";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import yaml from "yaml";

export default function(pi: Pi) {
  pi.on("session_start", () => {
    const lawsPath = join(pi.root, "iron-laws", "laws.yaml");
    try {
      const data = yaml.parse(readFileSync(lawsPath, "utf-8"));
      const lines = (data.laws ?? [])
        .filter((law: any) => law.shortform)
        .map((law: any) => `- ${law.shortform}`)
        .join("\n");
      pi.system_prompt_append(`Elixir/Phoenix Iron Laws (NON-NEGOTIABLE):\n${lines}`);
    } catch {
      // Best-effort. Pi continues without Iron Laws if YAML is missing.
    }
  });

  pi.on("tool_call", (call) => {
    if (call.tool !== "bash") return;
    const cmd: string = call.args?.command ?? "";
    if (/mix\s+ecto\.(reset|drop)/.test(cmd)) {
      call.block("BLOCKED: destructive ecto operation. Use a migration instead.");
    }
    if (/git\s+push\s+.*--force/.test(cmd)) {
      call.block("BLOCKED: --force push. Use --force-with-lease at minimum.");
    }
  });
}
